# Generated by Django 5.2.1 on 2025-05-09 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.CharField()),
                ('gender', models.CharField()),
                ('email', models.EmailField(max_length=254)),
                ('created', models.DateField()),
            ],
        ),
    ]
